title: Tech History
description: AI/ML, STT, TTS 그리고 VoIP 등 Brity Meeting과 관련된 개발 경험을 기록하는 기술 블로그
url: "https://junhokang76.github.io"
baseurl: "/techHistory"
lang: ko-KR
timezone: Asia/Seoul
author:
  name: Junho Kang

markdown: kramdown
permalink: /:year-:month-:title/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post

exclude:
  - README.md
  - vendor
  - node_modules
